server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ttlinh-O/config-server-repository
          default-label: main
          username: ttlinh-0
          password:
          clone-on-start: true
    fail-fast: true

  security:
    user:
      name: spring_cloud_user
      password: ENC(AVxMBejNka0hVcLGQ0+r3gFq3zbaDsbPWDCOuC/PoCSob3JCglJafbsuuoMDs7EhIKAi1ZbDskg7L7jrlFe/jA==)

jasypt:
  encryptor:
    password:

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

